name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Trigger the workflow when changes are pushed to the main branch
  workflow_dispatch: # Allow manual trigger of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js and install dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Build the Angular project
      - name: Build the project
        run: npm run build --prod

      - name: Upload the build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Clean up build directory
        run: rm -rf ./dist/*

      - name: Check out the repository
        uses: actions/checkout@v4

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: main  # Push to the main branch
          folder: dist/samuel-sudeep-portfolio  # Make sure to replace this with the correct build output folder
          token: ${{ secrets.GITHUB_TOKEN }}
