name: CI/CD for Angular App

on:
  push:
    branches:
      - master  # Trigger the workflow when code is pushed to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # You can change the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Build the Angular project
        run: npm run build -- --configuration production  # Build for production

      - name: Create Artifact for GitHub Pages
        run: |
          mkdir -p dist
          cp -r dist/samuel-sudeep-portfolio/* dist/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist/  # Upload dist folder as an artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the build job is successful before deploying
    permissions:
      contents: write  # Required for GitHub Pages deployment
      id-token: write  # Required for ID token authentication
      pages: write  # Required for deploying to GitHub Pages

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install angular-cli-ghpages
        run: npm install -g angular-cli-ghpages

      - name: List contents of dist folder
        run: |
          echo "Listing the contents of the dist folder:"
          ls -alh ./src  # List the contents of dist

      - name: Deploy to GitHub Pages
        run: |
          npx angular-cli-ghpages --dir=./src --repo=https://github.com/${{ github.repository }}.git
